### PR TITLE
Fix small mistake confusing students 

### PR DESCRIPTION
**Pull request by Ara225**
Hiya,
My buddies got really confused abot why npm start didn't work, They may not have read the readme.md properly, but still it's confusing :)

### CODE REVIEW

**Comment by textbook** [comment]
Thank you for the feedback! Unfortunately we can't apply this patch because it would break for production use. `npm start` is the conventional entrypoint used by e.g. Heroku, Render and other platforms, and it needs to point to the production build. That's why `npm run serve` is provided as an alternative.

**Comment by textbook** [comment]
You can't run the code in `server/` directly, because it wouldn't be getting transpiled (which `build:server` and `dev:server` do via Babel):
```
$ node server/server.js
(node:32365) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
path/to/server/server.js:1
import http from "http";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.14.0
```
This has come up before and is listed as one of the [common errors](https://github.com/textbook/starter-kit/wiki#common-errors).

**Comment by Ara225** [comment]
No worries, didn'tthink it through, sorry. Could we add a note to the readme to clarify?

**Comment by textbook** [comment]
The source for the README on this repo is [here](https://github.com/textbook/starter-kit/blob/main/bin/files/README.md) if you'd like to make suggestions, but I'm not sure what clarification I can usefully add - part of the problem is it's not getting read in the first place. There is a specific note in https://github.com/textbook/starter-kit/wiki/Scripts.

**Comment by Ara225** [comment]
Fair enough, sorry to be a pain, I'll remember for next year and prod my next set of trainees to read the  readme

**Comment by textbook** [comment]
Not a pain at all, it's great to get some input! There's [`#cyf-full-stack-starter-kit`](https://codeyourfuture.slack.com/archives/C021ATWS9A5) over in Slack too if you're interested.

**Pull request closed without merging**
