### PR TITLE
Tutor learner backend

### PR DESCRIPTION
**Pull request by TresorBipa**
## Naming Rules

Name your PR like this: ISSUENUMBER-Tutor-Learner-Profile-Backend-Tresor-Bipa

## Description

Write a summary of your change. Explain why you have made it.

## Related to

Make sure you include the issue number with a hash sign # so Github can link this PR to the right issue, like this:

Fixes #1

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have carefully reviewed my own code
- [ ] I have commented my code
- [ ] I have updated any documentation

### CODE REVIEW

**Review by EleMashige — APPROVED** [review]
Thank you Tresor. The code is fine.

**Comment by textbook** [comment]
I think you intended to make this to your team repo

**Comment by TresorBipa** [comment]
> I think you intended to make this to your team repo

Yes Jonathan, did i done something wrong?   what should i do or what i have to do in the future if i want  to push to my team main's branch

**Comment by textbook** [comment]
If you did intend to make this PR to your team's repo, then yes you did something wrong because this isn't your team's repo (it looks like that's https://github.com/AdvocateM/CodeCrafters-YIT). When opening a PR, check you're setting the right "base branch", the one you want your changes to be applied to (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request). 

Note this is why the instructions suggests using it as a template repo rather than forking, as GitHub's model (see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks) assumes that changes in a fork (in this case your team repo)  are intended to be merged to the upstream repo (this one).

**Pull request closed without merging**
